### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Manishkumar011** [zyra/ionic-super-tabs-example#25]
git submodule update
error: Server does not allow request for unadvertised object 5f1ace26cd3e89c2f9250502894d173e3c3abb78
Fetched in submodule path 'src/ionic2-super-tabs', but it did not contain 5f1ace26cd3e89c2f9250502894d173e3c3abb78. Direct fetching of that commit failed.

**Comment by rcnicke** [comment]
Same here

$ git submodule update
error: Server does not allow request for unadvertised object 3b0af6d194738781a4d254417593effbc69923db
Fetched in submodule path 'src/ionic2-super-tabs', but it did not contain 3b0af6d194738781a4d254417593effbc69923db. Direct fetching of that commit failed.
