### ISSUE TITLE
Overlapping tabs

### ISSUE THREAD

**Issue by zubliquzaini** [zyra/ionic-super-tabs-example#28]
I tried to achieve this in my project, but facing the same issue as #2.

![96589e54-2038-11e7-88d7-efa68b1f109c](https://user-images.githubusercontent.com/16085445/38973461-8548b440-43d8-11e8-9374-6be3d9c9d5f3.gif)

However, the tabs become overlapping and not scrollable.

![screenshot_2018-04-19-13-37-26](https://user-images.githubusercontent.com/16085445/38973480-a32c29c4-43d8-11e8-8f92-20c6d9b3fcf9.png)

I am using the latest version of super-tabs. Is there any solution for the tabs to become like one above? Help! Thank you in advance..

**Comment by kristoff2016** [comment]
Hello is it fixed ?
