### ISSUE TITLE
Not Working for Ionic 4

### ISSUE THREAD

**Issue by azamalvi** [zyra/ionic-super-tabs-example#32]
Last year I used "ionic2-super-tabs" in my ionic-3 project, and the Syntax was very short and easy. It also covers my requirement that tabs will be populated according to API response and only 1 page that will render all the tabs data according to the parameter.

**home.html**
```
<ion-content class="superTabContainer">
    <super-tabs scrollTabs class="superTabParent" toolbarColor="light">
        <super-tab *ngFor="let tab of tabs" [root]="tabPage" title="{{tab.name}}" [rootParams]="tab"></super-tab>
    </super-tabs>
</ion-content>
```
   
**home.ts**
```
import { SuperTabs } from "ionic2-super-tabs";
import { ProductListPage } from "../../pages/product-list/product-list";

`...................`
@ViewChild(SuperTabs) superTabs: SuperTabs;
tabPage = ProductListPage;
tabs = []; // array of tab
```

Now the same thing I want to use in my Ionic 4 App. Major issue is that there are 2 type of packages
**"@ionic-super-tabs/angular"** and **""ionic2-super-tabs""**. I tried both and none are working for me like they have **super-tabs-toolbar**  and **super-tabs-container** and this is not good that how can I handle this with only single page output like i do in ionic 3. My requirement is simple that I wan a swipe able tabs that render only page data according to parameter that will fetch the API and display to that

**Comment by ihadeed** [comment]
`@ionic-super-tabs/angular` should work for Ionic 4

I just published a new version and the example project is also updated.

Your code above would translate to:
```
<super-tabs>
  <super-tabs-toolbar slot="top" color="light" scrollable>
    <super-tab-button *ngFor"let t of tabs">
        <ion-label>{{ t.name }}</ion-label>
    </super-tab-button>
  </super-tabs-toolbar>
  <super-tabs-cotainer>
    <super-tab *ngFor="let t of tabs">
      <ion-nav [root]="tabPage" [rootParams]="tab"></ion-nav>
    </super-tab>
  </super-tabs-container>
</super-tabs>
```

**Comment by azamalvi** [comment]
@ihadeed thanks for this quick update.
I just download the latest example project and now when i run the project it throws an error
`Uncaught (in promise): Error: No component factory found for profilePage. Did you add it to @NgModule.entryComponents?`
tabs without pages are working fine, and Page tabs are blank

**Comment by azamalvi** [comment]
@ihadeed thanks for this quick update.
now only issue is that I am unable to get **[rootParams]** in tabPage(ProductListPage) constructor.
It looks like that it is directly rendring the HTML of [root] and not calling **constructor** nor **ngOnInit**.

**Comment by azamalvi** [comment]
I figured it out that **console.log** is not working but we can get **Params** in constructor. So it is working fine.
Now only issue is that when page open then it load all the data through the loop and hit all the APIs for tab page and this is not good. Tab Page content should be visible when user click on on any tab then it should hit the API and get response and render to the page.
It should not hit API 2nd time if it's tab is pressed before.

**Comment by ihadeed** [comment]
Lazy loading is not supported yet.

To fix issues with pages loading multiple times, probably a tracking function (`trackBy`) for the ngFor loops will do the trick.

**Comment by azamalvi** [comment]
Please try to implement lazy loading. it will reduce extra API hit.
Thanks for this great plugin. :)
