### ISSUE TITLE
Disable Swipe Option

### ISSUE THREAD

**Issue by lordnino** [zyra/ionic-super-tabs-example#34]
I have been trying to disable the swipe feature, with no luck. 

I'm using ionic 4 with angular.

So is there's a way to do this

**Comment by rgustavsson** [comment]
@lordnino 
Did you find such an option?

**Comment by rgustavsson** [comment]
Okey I found the solution here: 
https://zyra.github.io/ionic-super-tabs/components/super-tabs-container/
